stages:
  - test
  - build

variables:
  LANG: "en_US.UTF-8"

before_script:
  - flutter pub get

test:
  stage: test
  script:
    - flutter test
  tags:
    - mac
  only:
    - branches

build:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/*.apk
  tags:
    - mac
  only:
     - branches
