stages:
  #- test
  - build

variables:
  LANG: "en_US.UTF-8"

before_script:
  - flutter pub get
  - flutter pub run build_runner build --delete-conflicting-outputs

# test:
#   stage: test
#   script:
#     - flutter test
#   tags:
#     - macmini
#   only:
#     - branches

build:
  stage: build
  script:
    - flutter build apk --release
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/*.apk
  tags:
    - macmini
  only:
     - branches
