stages:
  - upgrade_flutter
  - build
  - deploy

variables:
  LANG: "en_US.UTF-8"

upgrade_flutter:
  stage: upgrade_flutter
  script:
    - flutter upgrade
    - flutter channel stable
    - flutter --version
  tags:
    - macmini
  only:
    - branches

build-ios:
  stage: build
  before_script:
    - flutter --version
    - sh pubs.sh
#    - cd ios
#    - pod repo update
#    - cd ..
  script:
    - flutter build ipa --release --export-method development
  artifacts:
    paths:
      - build/ios/ipa/*
    expire_in: 2 days
  tags:
    - macmini
  only:
    - branches

build-android:
  stage: build
  before_script:
    - printf ${ANDROID_RELEASE_KEY} | base64 -d > ./android/keys/release.keystore
    - flutter --version
    - sh pubs.sh
  script:
    - flutter build appbundle --release
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab
    expire_in: 2 days
  tags:
    - macmini
  only:
    - branches

generate-release-notes:
  stage: deploy
  script:
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git log --pretty="- %s (%h)" $CI_COMMIT_BEFORE_SHA..$CI_COMMIT_SHA > release-notes.txt
  artifacts:
    paths:
      - release-notes.txt
  tags:
    - macmini
  only:
    - develop_new

deploy-ios:
  stage: deploy
  needs:
    - job: build-ios
      artifacts: true
    - job: generate-release-notes
      artifacts: true
  script:
    - firebase appdistribution:distribute "build/ios/ipa/Advisor App.ipa" --app 1:986930839057:ios:931a04b3aeb905de5cbbb0 --token "$FIREBASE_TOKEN" --release-notes-file release-notes.txt --groups "Testers" --debug
  tags:
    - macmini
  only:
    - develop_new
deploy-android:
  stage: deploy
  needs:
    - job: build-android
      artifacts: true
    - job: generate-release-notes
      artifacts: true
  script:
    - firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --app 1:986930839057:android:16ca6e7b357f2ba95cbbb0 --token "$FIREBASE_TOKEN" --release-notes-file release-notes.txt --groups "Testers" --debug
  tags:
    - macmini
  only:
    - develop_new
