name: shared_advisor_interface
description: Shared advisor interface

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+46

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fortunica:
    path: ./brands/fortunica
  zodiac:
    path: ./brands/zodiac


  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  intl: ^0.18.0
  intl_utils: ^2.8.2
  rxdart: ^0.27.5
  connectivity_plus: ^2.3.9
  internet_connection_checker: ^1.0.0+1
  logger: ^1.1.0
  permission_handler: ^10.0.0
  flutter_local_notifications: ^12.0.3
  collection: ^1.16.0
  cached_network_image: 3.2.3
  image_picker: ^0.8.6+1
  flutter_svg: ^2.0.5
  flutter_bloc: ^8.1.2 #app state management
  auto_route: ^5.0.2
  equatable: ^2.0.5
  audioplayers: ^2.0.0
  flutter_sound: ^9.2.13
  audio_session: ^0.1.13
  flutter_media_metadata: ^1.0.0+1
  package_info_plus: ^4.0.0
  hive: ^2.2.3
  freshchat_sdk: ^0.10.3
  audible_mode: ^1.0.1

  # Firebase
  firebase_core: ^2.2.0
  firebase_messaging: ^14.3.0
  firebase_dynamic_links: ^5.0.5
  firebase_crashlytics: ^3.0.5
  firebase_remote_config: ^3.0.5
  firebase_analytics: ^10.0.5


  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  retrofit: ^4.0.1
  dio: ^5.0.0
  get_it: ^7.2.0
  web_fonts: ^1.1.1
  google_fonts: ^4.0.4
  loading_indicator: ^3.1.0
  open_mail_app: ^0.4.5
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.16
  crypto: ^3.0.2
  device_info_plus: ^9.0.0
  android_id: ^0.0.7
  modal_bottom_sheet: ^2.1.2
  auto_size_text: ^3.0.0
  app_tracking_transparency: ^2.0.3
  flutter_keyboard_visibility: ^5.4.0
  file: ^6.1.4
  disk_space: ^0.2.1
  uuid: ^3.0.7
  flutter_keyboard_size: ^1.0.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  mime: ^1.0.2
  flutter_cache_manager: ^3.3.0
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  share_plus: ^4.4.0
  blur: ^3.1.0
  charts_painter: ^2.0.0+2
  snapping_sheet: ^3.1.0
  system_date_time_format: ^0.7.0
  injectable: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #mockito: ^5.3.2
  #http_mock_adapter: ^0.3.3
  analyzer: 5.12.0
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.1.5
  build_runner: ^2.4.4

  auto_route_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: assets/splash_logo.png
  color: "#3975E9"
  image_dark: assets/splash_logo.png
  color_dark: "#366EBA"
  android_12:
    color: "#3975E9"
    color_dark: "#366EBA"
    image: assets/splash_logo_android12.png
    image_dark: assets/splash_logo_android12.png
  android: true
  ios: true
  web: false
  fullscreen: false

flutter_icons:
  image_path: 'assets/app_icon.png'
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/
    - assets/zodiac/
    - assets/zodiac/files/
    - assets/zodiac/vectors/
    - assets/vectors/
    - assets/images/
    - assets/images/flags/
    - assets/images/logos/
    - assets/vectors/zodiac_light/
    - assets/vectors/zodiac_dark/
    - assets/vectors/horoscopes/
    - assets/vectors/sessions_types/
    - assets/vectors/user_performance/
    - assets/zodiac/audios/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


flutter_gen:
  output: lib/generated/assets/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

