name: shared_advisor_interface
description: Shared advisor interface

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  rxdart: ^0.27.5
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  logger: ^1.1.0
  json_annotation: ^4.6.0
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  crypto: ^3.0.2
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1
  android_id: ^0.0.7


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3
  json_serializable: ^6.3.1

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/vectors/

  uses-material-design: true

flutter_intl:
  enabled: true
