name: shared_advisor_interface
description: Shared advisor interface

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  rxdart: ^0.27.5
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  url_launcher: ^6.1.6
  logger: ^1.1.0
  json_annotation: ^4.6.0
  flutter_svg: ^1.1.3
  google_fonts: ^3.0.1
  crypto: ^3.0.2
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1
  android_id: ^0.0.7
  loading_indicator: ^3.1.0
  open_mail_app: ^0.4.5
  modal_bottom_sheet: ^2.1.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  auto_size_text: ^3.0.0

  flutter_rating_bar: ^4.0.1
  equatable: ^2.0.5
  cached_network_image: 3.2.1
  image_picker: 0.8.5+3
  permission_handler: ^10.0.0
  smooth_page_indicator: ^1.0.0+2
  mime: ^1.0.2
  flutter_cache_manager: ^3.3.0
  connectivity_plus: ^2.3.9
  internet_connection_checker: ^1.0.0+1
  flutter_sound: ^9.2.13
  audio_session: ^0.1.6
  flutter_hooks: ^0.18.5+1


  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.2
  carousel_slider: ^4.1.1
  share_plus: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_gen: 4.3.0
  retrofit_generator: ^4.0.3
  json_serializable: ^6.3.1

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/vectors/
    - assets/images/
    - assets/images/brands/
    - assets/images/flags/
    - assets/images/logos/
    - assets/vectors/zodiac/
    - assets/vectors/sessions_types/
    - assets/vectors/user_performance/

  uses-material-design: true

flutter_gen:
  output: lib/generated/assets/
  line_length: 80

  integrations:
    flutter_svg: true

flutter_intl:
  enabled: true
