name: fortunica
description: Fortunica brand.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_advisor_interface:
    path: ../..

  flutter_localizations:
    sdk: flutter
  freezed: ^2.1.0+1
  hive: ^2.2.3
  intl: ^0.17.0
  #intl_utils: ^2.8.2
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  flutter_svg: ^1.1.3
  dio: ^4.0.6
  rxdart: ^0.27.5
  injectable: ^1.5.3
  get_it: ^7.2.0
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  android_id: ^0.0.7
  open_mail_app: ^0.4.5
  flutter_bloc: ^8.1.2
  bloc: ^8.1.0
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  collection: ^1.16.0
  loading_indicator: ^3.1.0
  cached_network_image: 3.2.3
  image_picker: ^0.8.6+1
  permission_handler: ^10.2.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.1.6
  charts_painter: ^2.0.0+2
  blur: ^3.1.0
  mime: ^1.0.2
  audioplayers: ^2.0.0
  flutter_media_metadata: ^1.0.0+1
  snapping_sheet: ^3.1.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_keyboard_size: ^1.0.1
  uuid: ^3.0.7
  storage_space: ^1.0.1+5
  smooth_page_indicator: ^1.0.0+2
  freshchat_sdk: ^0.10.3


  ### Firebase
  firebase_messaging: ^14.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: ^4.3.0

  json_serializable: ^6.5.4

  injectable_generator: ^1.5.4
  auto_route_generator: any

  build_runner: ^2.3.2
  retrofit_generator: ^4.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

flutter_intl:
  enabled: true
  class_name: SFortunica
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false