name: zodiac
description: Zodiac brand
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_advisor_interface:
    path: ../..
  hive: ^2.2.3
  intl: ^0.18.0
  intl_utils: ^2.8.2
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.5
  dio: ^5.0.0
  rxdart: ^0.27.5
  injectable: ^2.1.1
  get_it: ^7.2.0
  device_info_plus: ^9.0.0
  package_info_plus: ^4.0.0
  android_id: ^0.0.7
  open_mail_app: ^0.4.5
  flutter_bloc: ^8.1.2
  auto_route: ^5.0.2
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.3.0
  eventify: ^1.0.1
  retrofit: ^4.0.1
  collection: ^1.16.0
  blur: ^3.1.0
  charts_painter: ^2.0.0+2
  smooth_page_indicator: ^1.0.0+2
  loading_indicator: ^3.1.0
  cached_network_image: 3.2.3
  flutter_widget_from_html_core: ^0.9.1
  flutter_rating_bar: ^4.0.1
  freshchat_sdk: ^0.10.3
  url_launcher: ^6.1.6
  webview_flutter: ^4.0.7
  html: ^0.15.2
  pin_code_fields: ^7.4.0
  phone_numbers_parser: ^7.0.2
  avatar_glow: ^2.0.2
  vibration: ^1.7.6
  assets_audio_player: ^3.0.6
  flutter_slidable: ^3.0.0
  visibility_detector: ^0.4.0+2
  scrollview_observer: ^1.10.1
  snapping_sheet: ^3.1.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_keyboard_size: ^1.0.1

  audible_mode: ^1.0.1

  recaptcha:
   git:
      url: git@github.com:barges/flutter-recaptcha.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer: 5.12.0
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.6.2
  injectable_generator: ^2.1.5
  build_runner: ^2.4.4
  retrofit_generator: ^7.0.0

  auto_route_generator: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

flutter_intl:
  enabled: true
  class_name: SZodiac
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false