// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RecaptchaApi {
  func initialize(siteKey: String, completion: @escaping (Result<String, Error>) -> Void)
  func execute(recaptchaCustomAction: String, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RecaptchaApiSetup {
  /// The codec used by RecaptchaApi.
  /// Sets up an instance of `RecaptchaApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RecaptchaApi?) {
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.RecaptchaApi.initialize", binaryMessenger: binaryMessenger)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let siteKeyArg = args[0] as! String
        api.initialize(siteKey: siteKeyArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let executeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.RecaptchaApi.execute", binaryMessenger: binaryMessenger)
    if let api = api {
      executeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let recaptchaCustomActionArg = args[0] as! String
        api.execute(recaptchaCustomAction: recaptchaCustomActionArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      executeChannel.setMessageHandler(nil)
    }
  }
}
