name: adviqotech/adviser-app
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  upgrade_flutter:
    runs-on:
      - self-hosted
      - macmini
    if: startsWith(github.ref, 'refs/heads')
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - run: flutter upgrade
    - run: flutter channel stable
    - run: flutter --version
  build-ios:
    needs: upgrade_flutter
    runs-on:
      - self-hosted
      - macmini
    if: startsWith(github.ref, 'refs/heads')
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - run: flutter --version
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter build ipa --release --export-method development
    - uses: actions/upload-artifact@v3.1.3
      if: success()
      with:
        name: "${{ github.job }}"
        path: build/ios/ipa/*
  build-android:
    needs: upgrade_flutter
    runs-on:
      - self-hosted
      - macmini
    if: startsWith(github.ref, 'refs/heads')
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - run: printf ${ANDROID_RELEASE_KEY} | base64 -d > ./android/keys/release.keystore
    - run: flutter --version
    - run: flutter pub get
    - run: flutter pub run build_runner build --delete-conflicting-outputs
    - run: flutter build appbundle --release
    - uses: actions/upload-artifact@v3.1.3
      if: success()
      with:
        name: "${{ github.job }}"
        path: build/app/outputs/bundle/release/app-release.aab
  generate-release-notes:
    needs:
    - build-ios
    - build-android
    runs-on:
      - self-hosted
      - macmini
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v3.0.2
    - run: git fetch origin ${{ github.event.pull_request.base.ref }}
    - run: git log --pretty="- %s (%h)" $CI_COMMIT_BEFORE_SHA..${{ github.sha }} > release-notes.txt
    - uses: actions/upload-artifact@v3.1.3
      if: success()
      with:
        name: "${{ github.job }}"
        path: release-notes.txt
  deploy-ios:
    needs:
    - build-ios
    - generate-release-notes
    runs-on:
      - self-hosted
      - macmini
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v3.0.2
    - run: firebase appdistribution:distribute "build/ios/ipa/Advisor App.ipa" --app 1:986930839057:ios:931a04b3aeb905de5cbbb0 --token "$FIREBASE_TOKEN" --release-notes-file release-notes.txt --groups "Testers" --debug
  deploy-android:
    needs:
    - build-android
    - generate-release-notes
    runs-on:
      - self-hosted
      - macmini
    if: github.ref == 'refs/heads/develop'
    timeout-minutes: 60
    env:
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 50
        lfs: true
    - uses: actions/download-artifact@v3.0.2
    - run: firebase appdistribution:distribute build/app/outputs/bundle/release/app-release.aab --app 1:986930839057:android:16ca6e7b357f2ba95cbbb0 --token "$FIREBASE_TOKEN" --release-notes-file release-notes.txt --groups "Testers" --debug
